### PR TITLE
Add emoji - jcardoz

### PR DESCRIPTION
**Pull request by jcardoz**
EmojiDiv Checklist:

- [x] I have read EmojiDiv's contributing guidelines.
- [x] Create a div using your name as the ID.
- [x] Write a single div representation of your emoji using HTML and CSS (Not just adding an emoticon).
- [x] Set title of PR - 'Add emoji - [your div name]'
- [x] Upload Screenshot of your emoji in the details of the PR.
- [x] I had fun doing this! :wink:

Links to issue #1

### CODE REVIEW

**Comment by jcardoz** [comment]
Screen Shot 2020-10-14 at 8 47 21 PM

**Comment by jcardoz** [comment]
@kimberrypi - let me know if this works 👍

**Review by kimberrypi — APPROVED** [review]
yup, this works! thank you for contributing! hope you enjoyed!

**Pull request merged**
