### PR TITLE
Add crying laughing emoji

### PR DESCRIPTION
**Pull request by SmokinClove**
End result: 
image

### CODE REVIEW

**Review by kimberrypi — APPROVED** [review]
thank you for your contribution! :D

**Comment by SmokinClove** [comment]
Thank you for the opportunity :D btw is it okay to submit multiple PRs with each a different emoji (just wondering since, we use our name as id XD)

**Comment by kimberrypi** [comment]
Always open to make new ones!!! I'm glad you are enjoying!
Maybe add a number to your id? 
You can name the next div as `#SmokinClove2` or something :)

**Comment by SmokinClove** [comment]
Challenge accepted 👌

**Pull request merged**
